apiVersion: v1
kind: Service
metadata:
  name: {{ include "nodejs_test.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "nodejs_test.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort:  {{ .Values.deployment.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "nodejs_test.selectorLabels" . | nindent 4 }}
